
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module projectOne(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS

);



//=======================================================
//  REG/WIRE declarations
//=======================================================
reg outSafe; 
//reg locked; 
reg outClock;
reg activeVideo; 
reg [15:0] vValue;
reg [15:0] hValue;
reg slowClock;



//=======================================================
//  Structural coding
//=======================================================

video_pll video_pll(CLOCK_50, ~KEY[0], pixelClock, outSafe);

VTC VTC(pixelClock,
	KEY[0],
	VGA_HS,
	VGA_VS,
	activeVideo,
	hValue[15:0],
	vValue[15:0]
	);

PG PG(
    pixelClock,
    KEY[0],
    VGA_B[7:0],
    VGA_G[7:0],
    VGA_R[7:0],
    activeVideo,
	hValue[15:0],
	vValue[15:0],
	slowClock
);

clk_divider clk_divider(CLOCK_50, slowClock );

assign VGA_BLANK_N = 1;
assign VGA_SYNC_N = 0;
assign VGA_CLK = pixelClock;

endmodule
